(() => {
'use strict';
const log=document.getElementById('chat-log'),controls=document.getElementById('chat-controls');
let name='',procedure='';
const wa='https://wa.me/5541991491646';
function message(text,user=false){const el=document.createElement('p');el.className='bubble'+(user?' user':'');el.textContent=text;log.append(el);log.scrollTop=log.scrollHeight;}
function clear(){controls.replaceChildren();}
function option(label,action){const b=document.createElement('button');b.type='button';b.className='chat-option';b.textContent=label;b.addEventListener('click',action);controls.append(b);}
function link(label,text){const a=document.createElement('a');a.className='button';a.textContent=label;a.href=wa+'?text='+encodeURIComponent(text);a.target='_blank';a.rel='noopener noreferrer';controls.append(a);}
function home(){name='';procedure='';log.replaceChildren();clear();message('Olá! Seja bem-vindo à Odontocot Premium. Como podemos te ajudar hoje?');option('🦷 Agendar Avaliação de Implante / Prótese',()=>start());option('⚡ Conhecer nosso Laboratório Próprio',lab);option('📍 Ver Endereço e Horários',address);option('💬 Falar no WhatsApp',()=>{clear();message('Falar no WhatsApp',true);message('Nossa equipe está à disposição para conversar com você. Toque abaixo para continuar.');link('Continuar no WhatsApp','Olá! Gostaria de falar com a equipe da Odontocot Premium.');});}
function start(selected=''){clear();procedure=selected;message(selected?'Tenho interesse em '+selected+'.':'Quero agendar uma avaliação.',true);message('Que bom ter você por aqui! Como podemos te chamar?');const form=document.createElement('form');const label=document.createElement('label');label.htmlFor='patient-name';label.textContent='Seu nome';const input=document.createElement('input');input.id='patient-name';input.name='name';input.autocomplete='given-name';input.placeholder='Digite seu nome';input.required=true;input.maxLength=80;const submit=document.createElement('button');submit.type='submit';submit.className='button';submit.textContent='Continuar';form.append(label,input,submit);form.addEventListener('submit',e=>{e.preventDefault();name=input.value.trim();if(!name){input.setCustomValidity('Por favor, digite seu nome.');input.reportValidity();return;}message(name,true);clear();if(procedure){finish();return;}message('Obrigado, '+name+'! Qual procedimento você procura?');['Implante','Prótese','Outro'].forEach(item=>option(item,()=>{procedure=item;message(item,true);finish();}));});input.addEventListener('input',()=>input.setCustomValidity(''));controls.append(form);input.focus({preventScroll:true});}
function finish(){clear();message('Perfeito, '+name+'! Vamos levar seu interesse em '+procedure+' para nossa equipe. Ao tocar no botão, você poderá revisar e enviar a mensagem pelo WhatsApp.');link('Enviar solicitação no WhatsApp','Olá! Meu nome é '+name+'. Gostaria de agendar uma avaliação na Odontocot Premium Eucaliptos. Procedimento de interesse: '+procedure+'. Quais horários estão disponíveis?');}
function lab(){clear();message('Quero conhecer o laboratório próprio.',true);message('Nosso laboratório próprio integra a confecção das próteses ao planejamento clínico. Essa proximidade facilita ajustes, oferece mais precisão e ajuda a agilizar o tratamento. O prazo depende da avaliação de cada caso.');option('Quero agendar uma avaliação',()=>start());link('Conversar com a equipe','Olá! Gostaria de saber mais sobre o laboratório próprio da Odontocot Premium.');}
function address(){clear();message('Ver endereço e horários',true);message('Estamos na Av. Brasil, 1995 — Odontocot Eucaliptos. Para confirmar os horários de atendimento e receber a localização exata, fale com nossa equipe pelo WhatsApp.');link('Confirmar horários e localização','Olá! Gostaria de confirmar os horários e receber a localização da Odontocot Eucaliptos, Av. Brasil, 1995.');}
document.getElementById('restart').addEventListener('click',home);
document.querySelectorAll('[data-treatment]').forEach(b=>b.addEventListener('click',()=>{start(b.dataset.treatment);document.getElementById('autoatendimento').scrollIntoView({block:'start'});}));
document.querySelector('[data-lab]').addEventListener('click',lab);
const toggle=document.getElementById('menu-toggle'),nav=document.getElementById('navigation');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fechar navegação':'Abrir navegação');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Abrir navegação');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus();}});
document.getElementById('year').textContent=new Date().getFullYear();home();
})();
